### ISSUE TITLE
imp 2.11.1 conda packages not available

### ISSUE THREAD

**Issue by josan82** [salilab/conda-recipes#10]
I am looking for the conda packages for the version 2.11.1 of IMP. I have some dependencies in my project that do not allow to use 2.12 or higher.

I would need only the package for osx64, because I already obtained the linux package from the tpeulen conda channel.

I was wondering if I could create the conda package myself from your conda recipe and the source code of the version 2.11.1, but I see that the recipe is adapted for the version 2.13, so I suppose that the dependencies are not the same for 2.11.

Many thanks in advance for your help and congratulations for your work.

**Comment by benmwebb** [comment]
I would not recommend using an older version of IMP - they're not supported any more. You'd have a much easier job updating things to work with latest IMP. I'm not sure why you can't use 2.12 or higher - maybe you use older PMI classes such as `Representation`? Those are still present in latest IMP - you just need to change imports of `IMP.pmi` to `IMP.pmi1`.

I can't stop you from using an old version if you really want to. Of course the source code of IMP itself is available, as is the code for the conda recipe at https://github.com/salilab/conda-recipes/tree/ae9aed2/imp  - you would just need to check that out and use `conda build` to build it. I can't guarantee that that would work though - the conda folks are always changing things at their end.

**Comment by josan82** [comment]
OK, thank you for your quick answer. 

I'll try to figure out if it's possible to me to use IMP 2.12 or 2.13 by changing some other parts of the code, because for now, other dependencies make impossible to include IMP 2.12/13 due to dependency conflicts. If not, I think I won't have other option than trying to make the conda package of IMP 2.11 with the recipe you say.
