### ISSUE TITLE
MODELLER 9.25

### ISSUE THREAD

**Issue by S30194** [salilab/conda-recipes#11]
Please help me with this error message
file "script2.py",line 9, ?
aln.malign3d
file C....../alignment.py,line 338, in malign 3d
edit_file_ext)
_modeller.modeller error: fit2xyz_296E) number of equivalent position( (less than sign)3:0
please help

**Comment by benmwebb** [comment]
Not an issue with conda packaging; see https://salilab.org/modeller/contact.html
