### ISSUE TITLE
Apple Silicon & Conda

### ISSUE THREAD

**Issue by philspence** [salilab/conda-recipes#12]
Are there any plans to add a Conda package for osx-arm64? I know that homebrew has a package the works natively but that is not as flexible as Conda regarding python versions and supporting other packages that one may choose to use. Thanks.

**Comment by benmwebb** [comment]
Sure, once it's officially supported by the Anaconda folks, we'll make Apple Silicon packages for all our software (you don't say which package you're interested in; I'm assuming either IMP or Modeller). At the moment I'm only seeing Apple Silicon support in miniforge, and that's declared experimental.

**Comment by benmwebb** [comment]
FWIW, there's an `osx-arm64` package of Modeller now available at https://anaconda.org/salilab/modeller/. IMP is currently blocked by some of its dependencies not being available for Apple Silicon yet, see conda-forge/cgal-feedstock#64.

**Comment by benmwebb** [comment]
IMP packages for Apple Silicon are now available, so closing. Please reopen if you're interested in packages other than IMP or Modeller.

**Comment by uroshekic** [comment]
I am trying to install `dssp` with `conda install -c salilab dssp` on Apple with M2 processor, but I get the following error:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - dssp

Current channels:

  - https://conda.anaconda.org/salilab/osx-arm64
  - https://conda.anaconda.org/salilab/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Can you add support for `dssp` on Apple Silicon/ARM platform?
