### ISSUE TITLE
No module named 'fftw3'/No module named 'fftw'

### ISSUE THREAD

**Issue by 7yChris** [salilab/conda-recipes#2]
Hi!Thanks for the share of Fftw packages on conda.
However, I've successfully installed the packages with "conda install -c salilab fftw=3.3.4" on mac os and I can find the package installed in anaconda environment. But I just can't import the module with the name fftw3 or fftw, it always tells me that there is no such a module.
I wonder if you know why? 
My project deadline is coming soon and this is all I need!! I appreciate it if you can offer me a solution! Thank you!!

<img width="722" alt="2017-06-26 9 30 40" src="https://user-images.githubusercontent.com/26682554/27521680-2ef3340a-5a52-11e7-8ba7-9b60a384b886.png">
<img width="343" alt="2017-06-26 9 30 47" src="https://user-images.githubusercontent.com/26682554/27521683-315f3536-5a52-11e7-9a84-e3ef59d863fa.png">

By the way, the environment is MacOs Sierra 10.12.5, python 3.5.3!

**Comment by benmwebb** [comment]
These conda packages are of the fftw library itself, which is a C library. They don't include any Python wrappers (since fftw itself doesn't). You'll need to check out [pyFFTW](https://pypi.python.org/pypi/pyFFTW) for that.

**Comment by 7yChris** [comment]
Thank you!!
