### ISSUE TITLE
linux-64 DSSP 3.0.0 problem

### ISSUE THREAD

**Issue by oriolfornes** [salilab/conda-recipes#4]
The following error is recurrent for 3 different x64 linux machines:

```
$ conda install -c salilab dssp 
Solving environment: done

## Package Plan ##

  environment location: /home/ofornes/.miniconda2.7/envs/modcre

  added / updated specs: 
    - dssp


The following NEW packages will be INSTALLED:

    dssp: 3.0.0-hf484d3e_1 salilab

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
$ mkdssp
mkdssp: symbol lookup error: mkdssp: undefined symbol: _ZNK5boost15program_options22error_with_option_name23substitute_placeholdersERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Comment by benmwebb** [comment]
What version of boost are you using? This looks like your Boost is pre-C++11, but DSSP requires a C++11-enabled Boost. The DSSP dependencies should pull in boost 1.65.1 automatically which (on my Linux box at least) has the necessary symbols.

**Comment by oriolfornes** [comment]
Solved by removing and re-installing DSSP.

**Comment by benmwebb** [comment]
> I am using the right boost:

Actually you're not ;) Looks like both Anaconda and conda-forge provide an identically-named boost package, but they're built differently (I don't use conda-forge, so my package is built against Anaconda's boost, not the conda-forge package). That seems like a dumb decision on someone's part.  I'll see if I can force dssp to pull in the 'right' boost.

**Comment by oriolfornes** [comment]
Oh that will be awesome thanks!!!
