### ISSUE TITLE
IMP.mpi not found after install

### ISSUE THREAD

**Issue by fergaljd** [salilab/conda-recipes#6]
It looks like the new IMP 2.11 conda package does not include MPI, making it impossible to run well sampled simulations.

I get the following error:

```
>>>import IMP.mpi
Traceback (most recent call last):

  File "<ipython-input-10-fc345e804983>", line 1, in <module>
    import IMP.mpi

  File "/anaconda3/lib/python3.7/site-packages/IMP/mpi/__init__.py", line 21, in <module>
    _IMP_mpi = swig_import_helper()

  File "/anaconda3/lib/python3.7/site-packages/IMP/mpi/__init__.py", line 20, in swig_import_helper
    return importlib.import_module('_IMP_mpi')

  File "/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

ImportError: dlopen(/anaconda3/lib/python3.7/site-packages/_IMP_mpi.so, 2): Library not loaded: @rpath/libmpi_cxx.1.dylib
  Referenced from: /anaconda3/lib/python3.7/site-packages/_IMP_mpi.so
  Reason: image not found
```

**Comment by benmwebb** [comment]
Did you run your IMP script with `mpirun`? Which platform are you using?

The only recent MPI-related change is 3dfde53a, since the Anaconda folks dropped the `mpich2` package so we switched to the `mpich` package, which should be equivalent.

**Comment by fergaljd** [comment]
Yes, I am running my script with mpirun on macOS Mojave. I updated to IMP
2.11 using conda install -c salilab imp. It looks like the IMP.mpi library
was not installed by conda.

Fergal

**Comment by benmwebb** [comment]
Looks from your error message that `IMP.mpi` is there, but it can't find Anaconda's MPI library, `@rpath/libmpi_cxx.1.dylib`. Are you sure you installed the latest IMP though? On Mac IMP uses OpenMPI, and IMP 2.11.0 is linked against OpenMPI 3.1.3, which provides `@rpath/libmpi_cxx.40.dylib`. The `.1.dylib` is much older. Did you try a `conda update --all`?

**Comment by benmwebb** [comment]
Can you also post the output of `conda list -c` ? You probably have a mismatch somewhere.

**Comment by fergaljd** [comment]
Here it is:

defaults::_ipyw_jlab_nb_ext_conf-0.1.0-py37_0

defaults::alabaster-0.7.12-py37_0

defaults::anaconda-client-1.7.2-py37_0

defaults::anaconda-navigator-1.9.6-py37_0

defaults::appnope-0.1.0-py37_0

defaults::asn1crypto-0.24.0-py37_0

defaults::astroid-2.2.5-py37_0

defaults::attrs-19.1.0-py37_1

defaults::babel-2.7.0-py_0

defaults::backcall-0.1.0-py37_0

defaults::beautifulsoup4-4.7.1-py37_1

defaults::biopython-1.72-py37h6440ff4_0

defaults::blas-1.0-mkl

defaults::bleach-3.1.0-py37_0

defaults::bzip2-1.0.6-h1de35cc_5

conda-forge::ca-certificates-2019.6.16-hecc5488_0

defaults::cairo-1.14.12-hc4e6be7_4

conda-forge::certifi-2019.6.16-py37_0

defaults::cffi-1.12.3-py37hb5b8e2f_0

salilab::cgal-4.12-h0a44026_6

defaults::chardet-3.0.4-py37_1

defaults::click-7.0-py37_0

defaults::cloudpickle-1.2.1-py_0

defaults::clyent-1.2.2-py37_1

conda-forge::conda-4.7.5-py37_0

defaults::conda-build-3.17.6-py37_0

defaults::conda-env-2.6.0-1

defaults::conda-package-handling-1.3.10-py37_0

defaults::conda-verify-3.1.1-py37_0

defaults::cryptography-2.7-py37ha12b0ac_0

defaults::curl-7.64.0-ha441bb4_2

defaults::dbus-1.13.6-h90a0687_0

defaults::decorator-4.4.0-py37_1

defaults::defusedxml-0.6.0-py_0

defaults::docutils-0.14-py37_0

defaults::entrypoints-0.3-py37_0

defaults::expat-2.2.6-h0a44026_0

defaults::ffmpeg-4.0-h01ea3c9_0

salilab::fftw-3.3.4-1

defaults::filelock-3.0.12-py_0

conda-forge::fontconfig-2.13.1-h1027ab8_1000

defaults::freetype-2.9.1-hb4e5f40_0

defaults::future-0.17.1-py37_0

conda-forge::gdk-pixbuf-2.36.12-h76fb4c4_1001

defaults::gettext-0.19.8.1-h15daf44_3

conda-forge::ghostscript-9.22-h0a44026_1001

conda-forge::giflib-5.1.7-h01d97ff_1

defaults::glib-2.56.2-hd9629dc_0

defaults::glob2-0.6-py37_1

defaults::gmp-6.1.2-hb37e062_1

conda-forge::gobject-introspection-1.56.1-py37h8934b72_1001

defaults::graphite2-1.3.13-h2098e52_0

conda-forge::graphviz-2.40.1-ha626266_0

salilab::gsl-2.4-h884dcc4_2

defaults::harfbuzz-1.8.8-hb8d4a28_0

defaults::hdf5-1.10.2-hfa1e0ec_1

defaults::icu-58.2-h4b95b61_1

defaults::idna-2.8-py37_0

conda-forge::imagemagick-7.0.8_27-pl526h44c921f_0

defaults::imagesize-1.1.0-py37_0

salilab::imp-2.10.1-py37h0a44026_1

defaults::intel-openmp-2019.4-233

defaults::ipykernel-5.1.1-py37h39e3cac_0

defaults::ipython-7.5.0-py37h39e3cac_0

defaults::ipython_genutils-0.2.0-py37_0

defaults::ipywidgets-7.4.2-py37_0

defaults::isort-4.3.21-py37_0

defaults::jasper-2.0.14-h636a363_1

defaults::jbig-2.1-h4d881f8_0

defaults::jedi-0.13.3-py37_0

defaults::jinja2-2.10.1-py37_0

conda-forge::jpeg-9c-h1de35cc_1001

defaults::jsonschema-3.0.1-py37_0

defaults::jupyter_client-5.2.4-py37_0

defaults::jupyter_core-4.4.0-py37_0

defaults::jupyterlab-0.35.5-py37hf63ae98_0

defaults::jupyterlab_server-0.2.0-py37_0

defaults::keyring-18.0.0-py37_0

defaults::krb5-1.16.1-hddcf347_7

defaults::lazy-object-proxy-1.4.1-py37h1de35cc_0

defaults::libarchive-3.3.3-h786848e_5

defaults::libboost-1.67.0-hebc422b_4

conda-forge::libcroco-0.6.12-hb7dcfda_1001

defaults::libcurl-7.64.0-h051b688_2

defaults::libcxx-4.0.1-hcfea43d_1

defaults::libcxxabi-4.0.1-hcfea43d_1

defaults::libedit-3.1.20181209-hb402a30_0

salilab::libffi-3.2.1-0

defaults::libgfortran-3.0.1-h93005f0_2

defaults::libiconv-1.15-hdd342a3_7

defaults::liblief-0.9.0-h2a1bed3_2

defaults::libopencv-3.4.2-h7c891bd_1

defaults::libopus-1.3-h1de35cc_0

defaults::libpng-1.6.37-ha441bb4_0

defaults::libprotobuf-3.6.1-hd9629dc_0

conda-forge::librsvg-2.40.19-h7818f71_1000

defaults::libsodium-1.0.16-h3efe00b_0

defaults::libssh2-1.8.2-ha12b0ac_0

salilab::libtau-1.0.2-h0a44026_0

defaults::libtiff-4.0.10-hcb84e12_2

defaults::libvpx-1.7.0-h378b8a2_0

conda-forge::libwebp-1.0.2-h14d73da_2

conda-forge::libxcb-1.13-h1de35cc_1002

defaults::libxml2-2.9.9-hf6e021a_1

defaults::lz4-c-1.8.1.2-h1de35cc_0

defaults::lzo-2.10-h362108e_2

defaults::markupsafe-1.1.1-py37h1de35cc_0

defaults::mccabe-0.6.1-py37_1

defaults::mistune-0.8.4-py37h1de35cc_0

defaults::mkl-2019.4-233

defaults::mkl_fft-1.0.12-py37h5e564d8_0

defaults::mkl_random-1.0.2-py37h27c97d8_0

defaults::mpfr-4.0.1-h3018a27_3

defaults::mpi-1.0-openmpi

defaults::navigator-updater-0.2.1-py37_0

defaults::nbconvert-5.5.0-py_0

defaults::nbformat-4.4.0-py37_0

defaults::ncurses-6.1-h0a44026_1

defaults::notebook-5.7.8-py37_0

defaults::numpy-1.16.4-py37hacdab7b_0

defaults::numpy-base-1.16.4-py37h6575580_0

defaults::numpydoc-0.9.1-py_0

defaults::olefile-0.46-py37_0

openbabel::openbabel-2.4.1-py37_5

defaults::opencv-3.4.2-py37h6fd60c2_1

conda-forge::openjpeg-2.3.1-hc1feee7_0

defaults::openmpi-3.1.3-hfa1e0ec_1

defaults::openssl-1.1.1c-h1de35cc_1

defaults::packaging-19.0-py37_0

defaults::pandas-0.24.2-py37h0a44026_0

defaults::pandoc-2.2.3.2-0

defaults::pandocfilters-1.4.2-py37_1

conda-forge::pango-1.40.14-he752989_2

defaults::parso-0.4.0-py_0

defaults::pcre-8.43-h0a44026_0

conda-forge::perl-5.26.2-haec8ef5_1005

defaults::pexpect-4.7.0-py37_0

defaults::pickleshare-0.7.5-py37_0

defaults::pillow-6.0.0-py37hb68e598_0

defaults::pip-19.1.1-py37_0

defaults::pixman-0.38.0-h1de35cc_0

conda-forge::pkg-config-0.29.2-h112b980_1005

defaults::pkginfo-1.5.0.1-py37_0

defaults::prometheus_client-0.6.0-py37_0

defaults::prompt_toolkit-2.0.9-py37_0

defaults::protobuf-3.6.1-py37h0a44026_0

defaults::psutil-5.6.2-py37h1de35cc_0

conda-forge::pthread-stubs-0.4-h1de35cc_1001

defaults::ptyprocess-0.6.0-py37_0

defaults::py-lief-0.9.0-py37h1413db1_2

defaults::py-opencv-3.4.2-py37h7c891bd_1

defaults::pycodestyle-2.5.0-py37_0

defaults::pycosat-0.6.3-py37h1de35cc_0

defaults::pycparser-2.19-py37_0

defaults::pyflakes-2.1.1-py37_0

defaults::pygments-2.4.2-py_0

defaults::pylint-2.3.1-py37_0

defaults::pyopenssl-19.0.0-py37_0

defaults::pyparsing-2.4.0-py_0

defaults::pyqt-5.9.2-py37h655552a_2

defaults::pyrsistent-0.14.11-py37h1de35cc_0

pypi::pysam-0.15.2-pypi_0

defaults::pysocks-1.7.0-py37_0

defaults::python-3.7.1-haf84260_7

defaults::python-dateutil-2.8.0-py37_0

defaults::python-libarchive-c-2.8-py37_6

defaults::python.app-2-py37_9

defaults::pytz-2019.1-py_0

defaults::pyyaml-5.1-py37h1de35cc_0

defaults::pyzmq-18.0.0-py37h0a44026_0

defaults::qt-5.9.7-h468cd18_1

defaults::qtawesome-0.5.7-py37_1

defaults::qtconsole-4.5.1-py_0

defaults::qtpy-1.7.1-py_0

defaults::readline-7.0-h1de35cc_5

defaults::requests-2.22.0-py37_0

defaults::rope-0.14.0-py_0

defaults::ruamel_yaml-0.15.46-py37h1de35cc_0

defaults::scipy-1.2.1-py37h1410ff5_0

defaults::send2trash-1.5.0-py37_0

defaults::setuptools-41.0.1-py37_0

defaults::sip-4.19.8-py37h0a44026_0

defaults::six-1.12.0-py37_0

defaults::snowballstemmer-1.9.0-py_0

defaults::soupsieve-1.8-py37_0

defaults::sphinx-2.1.2-py_0

defaults::sphinxcontrib-applehelp-1.0.1-py_0

defaults::sphinxcontrib-devhelp-1.0.1-py_0

defaults::sphinxcontrib-htmlhelp-1.0.2-py_0

defaults::sphinxcontrib-jsmath-1.0.1-py_0

defaults::sphinxcontrib-qthelp-1.0.2-py_0

defaults::sphinxcontrib-serializinghtml-1.1.3-py_0

defaults::spyder-3.3.6-py37_0

defaults::spyder-kernels-0.5.1-py37_0

defaults::sqlite-3.28.0-ha441bb4_0

bioconda::star-2.7.0f-0

defaults::terminado-0.8.2-py37_0

defaults::testpath-0.4.2-py37_0

defaults::tk-8.6.8-ha441bb4_0

defaults::tornado-6.0.2-py37h1de35cc_0

defaults::tqdm-4.32.1-py_0

defaults::traitlets-4.3.2-py37_0

defaults::urllib3-1.24.2-py37_0

defaults::wcwidth-0.1.7-py37_0

defaults::webencodings-0.5.1-py37_1

defaults::wheel-0.33.4-py37_0

defaults::widgetsnbextension-3.4.2-py37_0

defaults::wrapt-1.11.2-py37h1de35cc_0

defaults::wurlitzer-1.0.2-py37_0

pypi::xlrd-1.2.0-pypi_0

conda-forge::xorg-kbproto-1.0.7-h1de35cc_1002

conda-forge::xorg-libice-1.0.9-h01d97ff_1004

conda-forge::xorg-libsm-1.2.3-h01d97ff_1000

conda-forge::xorg-libx11-1.6.7-h1de35cc_1000

conda-forge::xorg-libxau-1.0.9-h1de35cc_0

conda-forge::xorg-libxdmcp-1.1.3-h01d97ff_0

conda-forge::xorg-libxext-1.3.4-h01d97ff_0

conda-forge::xorg-libxrender-0.9.10-h01d97ff_1002

conda-forge::xorg-libxt-1.1.5-h1de35cc_1002

conda-forge::xorg-renderproto-0.11.1-h1de35cc_1002

conda-forge::xorg-xextproto-7.3.0-h1de35cc_1002

conda-forge::xorg-xproto-7.0.31-h1de35cc_1007

defaults::xz-5.2.4-h1de35cc_4

defaults::yaml-0.1.7-hc338f04_2

defaults::zeromq-4.3.1-h0a44026_3

defaults::zlib-1.2.11-h1de35cc_3

defaults::zstd-1.3.7-h5bba6e5_0

**Comment by benmwebb** [comment]
> salilab::imp-2.10.1-py37h0a44026_1

Ah, there's your problem. You have the newest OpenMPI, but an older IMP, which is linked against the older OpenMPI (#7 should "fix" this by preventing you from upgrading OpenMPI if you have IMP installed). What happens if you try `conda update imp`? My guess is you have a dependency conflict which is preventing IMP 2.11 from being installed.

**Comment by fergaljd** [comment]
I managed to workaround by uninstalling imp and openmpi, and reinstalling imp. This seems to work.

**Comment by benmwebb** [comment]
Great! I guess Anaconda just got confused somewhere.
