### ISSUE TITLE
CondaHTTPError

### ISSUE THREAD

**Issue by rsieskind** [salilab/conda-recipes#8]
Hi all,

When using the command given on the anaconda cloud website:

>conda install -c salilab modeller

I get the following error message and I do not succeed in figuring out what is happening.

Solving environment: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/pro/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/pro/noarch/repodata.json.bz2 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))

Does anyone encounter the same difficulties? Does anyone have a solution?

Best,

Rémi

**Comment by benmwebb** [comment]
This is certainly not a Modeller-specific error, but one of a number of issues with your conda installation. See for example ContinuumIO/anaconda-issues#6424.

If I were in your position, I would probably try a fresh install of the latest Anaconda/Miniconda first.
